{"name": "test_loginFailMethod", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <AppiumFrameWork.tests.LoginTest.LoginTest testMethod=test_loginFailMethod>\n\n    @pytest.mark.run(order=3)\n    def test_loginFailMethod(self):\n        cl.allureLogs(\"App Opened\")\n        self.gt.clickLoginButton()\n        self.gt.enterEmail()\n        self.gt.enterPassword2()\n        self.gt.clickLoginButton2()\n        self.gt.verifyWrongCredential()\n>       self.gt.verifyAdminScreen()\n\nLoginTest.py:40: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <AppiumFrameWork.pages.LoginPage.LoginPage object at 0x000002166E5459F0>\n\n    def verifyAdminScreen(self):\n        adminScreen = self.isDisplayed(self._pageTitle, \"text\")\n>       assert adminScreen == True\nE       AssertionError\n\n..\\pages\\LoginPage.py:47: AssertionError"}, "steps": [{"name": "App Opened", "status": "passed", "start": 1699003629183, "stop": 1699003629183}, {"name": "Click on Login Button", "status": "passed", "start": 1699003629881, "stop": 1699003629881}, {"name": "Entered email id", "status": "passed", "start": 1699003631430, "stop": 1699003631430}, {"name": "Entered Password", "status": "passed", "start": 1699003632499, "stop": 1699003632499}, {"name": "Clicked on Login Button in Login Screen", "status": "passed", "start": 1699003633057, "stop": 1699003633057}, {"name": "Wrong Credentials Handling Successfull", "status": "passed", "start": 1699003633599, "stop": 1699003633600}], "attachments": [{"name": "text", "source": "b016c101-eefa-4e6f-9226-22ffef232a62-attachment.png", "type": "image/png"}, {"name": "log", "source": "1017787b-1b21-4a4a-a903-0386f96672ef-attachment.txt", "type": "text/plain"}], "start": 1699003629183, "stop": 1699003659475, "uuid": "ce4a09f4-ab29-49b9-9525-920ec927c515", "historyId": "45b2d65b13d171810cc1abbc024a91f8", "testCaseId": "c0c119c5b9dbef534dea94dd53642878", "fullName": "AppiumFrameWork.tests.TestSuite.LoginTest#test_loginFailMethod", "labels": [{"name": "tag", "value": "run(order=3)"}, {"name": "tag", "value": "@pytest.mark.usefixtures('beforeClass', 'beforeMethod')"}, {"name": "parentSuite", "value": "AppiumFrameWork.tests"}, {"name": "suite", "value": "TestSuite"}, {"name": "subSuite", "value": "LoginTest"}, {"name": "host", "value": "DESKTOP-1E9OV05"}, {"name": "thread", "value": "31228-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "AppiumFrameWork.tests.TestSuite"}]}